version: '3'

services:
  db:
    image: postgres:9.6.10
    env_file: .env
    volumes:
      - .pgdata:/var/lib/postgresql/data


  backend:
    env_file: .env
    build:
      dockerfile: Dockerfile-prod
      context: ./backend
      args:
        - PROXY=${PROXY}
        - DB_NAME=${DB_NAME}
        - DB_USER=${DB_USER}
        - DB_PORT=${DB_PORT}
        - DB_ADDRES=${DB_ADDRESS}
        - DEBUG=${DEBUG}
        - SECRET_KEY=${SECRET_KEY}
    entrypoint: wait-for-it.sh db:5432 --
    command: bash -c "./manage.py migrate && gunicorn --access-logfile - zpp.wsgi:application -w 3 -b :8000"
    depends_on:
      - db
    volumes:
      - ./scripts:/usr/src/app/scripts
    restart: always


  frontend:
    env_file: .env
    build:
      dockerfile: Dockerfile-prod
      context: ./frontend
      args:
        - PROXY=${PROXY}
    ports:
      - 127.0.0.1:${FRONTEND_PORT}:80
    restart: always
