export const RESTAURANRS_GET_RESTAURANTS = 'RESTAURANRS_GET_RESTAURANTS';
export const RESTAURANT_GET_RESTAURANTT = 'RESTAURANT_GET_RESTAURANT';
export const REVIEWS_GET_REVIEWS = 'REVIEWS_GET_REVIEWS';
