// AUTH types
export const AUTH_SAVE_USER = 'AUTH_SAVE_USER';
export const AUTH_DELETE_USER = 'AUTH_DELETE_USER';
export const AUTH_SAVE_INFO = 'AUTH_SAVE_INFO';

// RESTAURANT types
export const RESTAURANTS_LIST = 'RESTAURANTS_LIST';
export const RESTAURANT_ID = 'RESTAURANT_ID';
export const REVIEWS_LIST = 'REVIEWS_LIST';
