# Generated by Django 2.1.2 on 2018-12-10 14:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='Poland', max_length=40)),
                ('city', models.CharField(default='Wroclaw', max_length=40)),
                ('street', models.CharField(max_length=70)),
                ('local_number', models.CharField(max_length=5)),
                ('postcode', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('features', models.CharField(choices=[('WiFi', 'WiFi'), ('Toliet', 'Toliet'), ('Dogs allowed', 'Dogs allowed'), ('Climatization', 'Climatization'), ('Outdoor tabkle', 'Outdoor tabkle')], max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.date.today)),
                ('receipt_number', models.CharField(default='#', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Restaurant name', max_length=100)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('food_type', models.CharField(default='Kuchnia polska', max_length=40)),
                ('price_rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('vegan_option', models.BooleanField(default=False)),
                ('vegetarian_option', models.BooleanField(default=False)),
                ('short_review', models.CharField(default='Short Review', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.PositiveIntegerField(choices=[(1, 'Awful'), (2, 'Not good'), (3, 'Average'), (4, 'Awesome'), (5, 'Best Place EVER')], default=1)),
                ('review', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='opinion',
            name='climate_review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='climateReview', to='api.Review'),
        ),
        migrations.AddField(
            model_name='opinion',
            name='food_review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foodReview', to='api.Review'),
        ),
        migrations.AddField(
            model_name='opinion',
            name='price_review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='priceReview', to='api.Review'),
        ),
        migrations.AddField(
            model_name='opinion',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant', to='api.Restaurant'),
        ),
        migrations.AddField(
            model_name='opinion',
            name='staff_review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffReview', to='api.Review'),
        ),
        migrations.AddField(
            model_name='features',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Opinion'),
        ),
        migrations.AddField(
            model_name='address',
            name='restaurant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='api.Restaurant'),
        ),
    ]
