# Generated by Django 2.1.2 on 2018-10-22 23:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='Poland', max_length=40)),
                ('city', models.CharField(default='Wroclaw', max_length=40)),
                ('street', models.CharField(max_length=70)),
                ('local_number', models.CharField(max_length=5)),
                ('postcode', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.date.today)),
                ('receipt_number', models.CharField(default='#', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Restaurant name', max_length=100)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('food_type', models.CharField(default='Kuchnia polska', max_length=40)),
                ('avg_rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('price_rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('vegan_option', models.BooleanField(default=False)),
                ('vegetarian_option', models.BooleanField(default=False)),
                ('short_review', models.CharField(default='Short Review', max_length=300)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='api.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.PositiveIntegerField(choices=[(1, 'Awful'), (2, 'Not good'), (3, 'Average'), (4, 'Awesome'), (5, 'Best Place EVER')], default=1)),
                ('review', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.CreateModel(
            name='ChangingRoom',
            fields=[
                ('feature_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Feature')),
            ],
            bases=('api.feature',),
        ),
        migrations.CreateModel(
            name='DogsAllowed',
            fields=[
                ('feature_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Feature')),
            ],
            bases=('api.feature',),
        ),
        migrations.CreateModel(
            name='Toilet',
            fields=[
                ('feature_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Feature')),
            ],
            bases=('api.feature',),
        ),
        migrations.CreateModel(
            name='Wifi',
            fields=[
                ('feature_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Feature')),
            ],
            bases=('api.feature',),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='features',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='api.Feature'),
        ),
        migrations.AddField(
            model_name='opinion',
            name='climate_review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='climateReview', to='api.Review'),
        ),
        migrations.AddField(
            model_name='opinion',
            name='food_review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foodReview', to='api.Review'),
        ),
        migrations.AddField(
            model_name='opinion',
            name='price_review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='priceReview', to='api.Review'),
        ),
        migrations.AddField(
            model_name='opinion',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant', to='api.Restaurant'),
        ),
        migrations.AddField(
            model_name='opinion',
            name='staff_review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffReview', to='api.Review'),
        ),
    ]
