# Generated by Django 2.1.2 on 2018-10-22 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20181022_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='features',
        ),
    ]
