# Generated by Django 2.1.2 on 2018-12-10 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='videofile',
            new_name='imagefile',
        ),
    ]
