# Generated by Django 2.1.2 on 2018-12-10 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20181210_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
