# Generated by Django 2.1.2 on 2018-12-10 15:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20181210_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(default=django.utils.timezone.localtime, max_length=100),
        ),
    ]
