# Generated by Django 2.1.2 on 2018-12-10 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20181210_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='restaurant',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.Restaurant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(blank=True, default='2018-12-10 15:57:05.731294', editable=False, max_length=100, null=True),
        ),
    ]
