# Generated by Django 2.1.2 on 2019-01-15 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20181210_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion',
            name='short_review',
            field=models.CharField(default='Short Review', max_length=300),
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(blank=True, default='2019-01-15 00:35:39.233016', editable=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='api.Restaurant'),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='climate_review',
            field=models.PositiveIntegerField(choices=[(1, 'Awful'), (2, 'Not good'), (3, 'Average'), (4, 'Awesome'), (5, 'Best EVER')], default=1),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='food_review',
            field=models.PositiveIntegerField(choices=[(1, 'Awful'), (2, 'Not good'), (3, 'Average'), (4, 'Awesome'), (5, 'Best EVER')], default=1),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='price_review',
            field=models.PositiveIntegerField(choices=[(1, 'Awful'), (2, 'Not good'), (3, 'Average'), (4, 'Awesome'), (5, 'Best EVER')], default=1),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='staff_review',
            field=models.PositiveIntegerField(choices=[(1, 'Awful'), (2, 'Not good'), (3, 'Average'), (4, 'Awesome'), (5, 'Best EVER')], default=1),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
