# Generated by Django 2.1.2 on 2019-01-21 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20190115_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(blank=True, default='2019-01-21 19:17:28.341086', editable=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
